# Generated by Django 6.0.5 on 2026-05-28 23:33

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='Full Name')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Date of Birth')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
                'ordering': ['full_name'],
                'indexes': [models.Index(fields=['full_name'], name='app_student_full_na_f777d8_idx')],
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='Full Name')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Phone')),
                ('degree', models.CharField(choices=[('none', 'None'), ('bachelor', 'Bachelor'), ('master', 'Master'), ('phd', 'PhD'), ('doctor', 'Doctor of Science')], default='none', max_length=20, verbose_name='Academic Degree')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Teacher',
                'verbose_name_plural': 'Teachers',
                'ordering': ['full_name'],
                'indexes': [models.Index(fields=['full_name'], name='app_teacher_full_na_7dc85a_idx')],
                'constraints': [models.UniqueConstraint(fields=('email',), name='unique_teacher_email')],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Subject Name')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('students', models.ManyToManyField(blank=True, related_name='subjects', to='app.student', verbose_name='Students')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subjects', to='app.teacher', verbose_name='Teacher')),
            ],
            options={
                'verbose_name': 'Subject',
                'verbose_name_plural': 'Subjects',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SchoolClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)], verbose_name='Class Number')),
                ('abbreviation', models.CharField(max_length=10, unique=True, verbose_name='Abbreviation')),
                ('full_name', models.CharField(blank=True, max_length=100, verbose_name='Full Name')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('students', models.ManyToManyField(blank=True, related_name='classes', to='app.student', verbose_name='Students')),
            ],
            options={
                'verbose_name': 'School Class',
                'verbose_name_plural': 'School Classes',
                'ordering': ['number', 'abbreviation'],
                'constraints': [models.UniqueConstraint(fields=('abbreviation',), name='unique_class_abbreviation'), models.CheckConstraint(condition=models.Q(('number__gte', 1), ('number__lte', 9)), name='class_number_range')],
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Grade')),
                ('grade_type', models.CharField(choices=[('none', 'None'), ('classwork', 'Classwork'), ('homework', 'Homework'), ('test', 'Test'), ('project', 'Project')], default='none', max_length=20, verbose_name='Grade Type')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('students', models.ManyToManyField(blank=True, related_name='grades', to='app.student', verbose_name='Students')),
                ('subjects', models.ManyToManyField(blank=True, related_name='grades', to='app.subject', verbose_name='Subjects')),
            ],
            options={
                'verbose_name': 'Grade',
                'verbose_name_plural': 'Grades',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at'], name='app_grade_created_1fcb4e_idx'), models.Index(fields=['value'], name='app_grade_value_b0cd82_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('value__gte', 1), ('value__lte', 5)), name='grade_value_range')],
            },
        ),
        migrations.AddConstraint(
            model_name='subject',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_subject_name'),
        ),
    ]
